language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: sWMRGS16FTl7uKyizasXk4xo5OGTksFuovSGurU56ItKmOgydX6e1piQSi1jp11oXMvtP3JMYioQjePpBJYgiDCNWK6SCPUk/2I/WDzdJ62YEu2ubM/wNgQb6GI+jnbDNL9lE7Vfa9FcylznJ9pNidmdRud4ZDj3sqGkzl6eYaXOJycSqe7V45zRSH7uVnTowLqpBlSJEPvzkUhakqO1QivW0+yUBD4DTyWhxUVDjfusw+ryAhwtrBhQ986loeqOkZ6Sh0+3wZUkZerih8bJ8elUZ2xZJyQgfmBGVvbCisscXPVUCyxLGQ4xCjCA3rhxXNrgFb+GuWMqufKMC+yaP3Jm7JOkTpzwJJqsfPm1Fl0V5fJJACrVdDiRDJbMoYqDgN9YoTgKUny8furd3D3IMXEntlGQrNDp/GsVNZ6XZup46zGbkxYwAuNcBSK7YczWrGWHkujAoHhrLfrf18SQrzI0GNKa8aoB1NSG1hMX2or5Sw4F1wdQcjXStXM2KD9Ir1ROKe665AQQD/rJmW1oOrNSxYl1Z8Pu5GSSPSTWepyy1WXFCHyhzt8v0WgAXeCO43kLRo7ch8rRtK811ifcJbOy5Tmo1kNg+rRRdHVrQ9hUqPn52FDCeIQO4himwtdKjjSIN/RPTH+0hzyLIXrT7v9+TOKqJhbPD4VJ8fxo4Qs=
  app: stark-atoll-37312